name: DVC Tracking with Github Actions
on: [push]
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running_updates
        env: 
          GH_TOKEN: ${{ github.token }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          pip install -r requirements.txt 
          dvc repro
          dvc metrics diff --md remotes/origin/master
      #    gh pr comment ${{github.event.pull_request.number}} -F report.md
          
