name: Access File from Master Branch

on: [push]
jobs:
  access-file-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master  # specify the branch you want to access the file from

    - name: Display file content
      run: cat master/metrics.json  # adjust the path accordingly

    # Add more steps as needed for your workflow
